# Base image for the app
# This image contains all the dependencies

FROM python:3.8-slim

# Install python requirements
COPY requirements.txt .
RUN python -m pip install -r requirements.txt

# Install requirements needed by QT
RUN apt-get update && apt-get install '^libxcb.*-dev' libx11-xcb-dev libglu1-mesa-dev libxrender-dev libxi-dev libxkbcommon-dev libxkbcommon-x11-dev ffmpeg libsm6 libxext6 -y
